// Generated by assets/desktop/palette/gen-palette.py — do not edit by hand.
// Firewatch Dusk — Material You (tonal_spot) from #e8931c.
pragma Singleton

import QtQuick

QtObject {
    readonly property color primary: "#eebe8b"
    readonly property color fgPrimary: "#593912"
    readonly property color primaryContainer: "#6e4b23"
    readonly property color fgPrimaryContainer: "#ffddbd"
    readonly property color secondary: "#e0c1a3"
    readonly property color secondaryContainer: "#4c3821"
    readonly property color tertiary: "#fafebb"
    readonly property color fgTertiary: "#5e622e"
    readonly property color tertiaryContainer: "#ebf0ad"
    readonly property color error: "#f97758"
    readonly property color fgError: "#450900"
    readonly property color surface: "#0f0e0c"
    readonly property color surfaceDim: "#0f0e0c"
    readonly property color surfaceBright: "#2f2b29"
    readonly property color surfaceContainerLowest: "#000000"
    readonly property color surfaceContainerLow: "#151311"
    readonly property color surfaceContainer: "#1b1917"
    readonly property color surfaceContainerHigh: "#221f1d"
    readonly property color surfaceContainerHighest: "#282523"
    readonly property color fgSurface: "#ebe4e0"
    readonly property color fgSurfaceVariant: "#b0aaa6"
    readonly property color outline: "#797471"
    readonly property color outlineVariant: "#4b4745"
    readonly property color inverseSurface: "#fdf8f7"

    // How opaque our cards sit on the wallpaper.
    readonly property real cardAlpha: 0.82
    readonly property color card: Qt.rgba(surfaceContainer.r, surfaceContainer.g,
                                          surfaceContainer.b, cardAlpha)
    readonly property color cardHigh: Qt.rgba(surfaceContainerHigh.r, surfaceContainerHigh.g,
                                              surfaceContainerHigh.b, cardAlpha)

    // Severity ramp, shared by every gauge/bar so "getting full" always looks
    // the same whether it is a disk or a Claude quota.
    readonly property color good: tertiary
    readonly property color warn: primary
    readonly property color high: "#c9a900"
    readonly property color crit: error

    function severityColor(percent) {
        if (percent >= 95) return crit;
        if (percent >= 80) return high;
        if (percent >= 50) return warn;
        return good;
    }
}
