palette = "rice"
format = """
[░▒▓](crust)\
$os\
[](bg:lavender fg:crust)\
$directory\
[ ](fg:lavender bg:surface0)\
$git_branch\
$git_status\
$hg_branch\
[ ](fg:surface0 bg:crust)\
[▓▒░](crust)\
[ ◦•](surface2)\
$fill\
[•◦ ](surface2)\
[░▒▓](crust)\
[ ](fg:surface0 bg:crust)\
$status\
$cmd_duration\
[ ](fg:crust bg:surface0)\
$battery\
[▓▒░](crust)
[·](surface0)\
[·](surface2)\
[•](overlay1)\
[ ](teal)\
"""

[fill]
symbol = "·"
style = "surface2"

[directory]
style = "fg:surface0 bg:lavender"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~" = "  "
"Applications" = "  "
"Desktop" = "  "
"Developer" = "  "
"Documents" = " 󰈙 "
"Downloads" = "  "
"Games" = "  "
"GitHub" = "  "
"Library" = "  "
"Movies" = "  "
"Music" = "  "
"Pictures" = "  "
"Projects" = "  "
"Public" = "  "
"Screenshots" = " 󱣴 "
"Videos" = "  "
"Thunderbird" = "   "
"source" = " 󰈹 "
"comm" = "  "

[git_branch]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol $branch ](fg:lavender bg:surface0)]($style)'

[git_status]
style = "bg:surface0"
format = '[[($all_status$ahead_behind )](fg:lavender bg:surface0)]($style)'

[hg_branch]
disabled = false
symbol = ""
style = "bg:surface0"
format = '[[ $symbol $branch ](fg:lavender bg:surface0)]($style)'

[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true
style = "fg:text bg:surface0"
format = '[$duration]($style)'

[status]
symbol = '  '
success_symbol = '  '
not_executable_symbol = '  '
not_found_symbol = '  '
map_symbol = true
disabled = false
style = 'fg:text bg:surface0'
format = '[$symbol]($style)'

[battery]
disabled = false
full_symbol = ''
charging_symbol = '⚡️'
discharging_symbol = ''
unknown_symbol = ''
empty_symbol = ''
format = '[[ $symbol $percentage ](fg:text bg:crust)]($style)'

[[battery.display]]
threshold = 25
discharging_symbol = ''
style = 'fg:yellow bg:crust'

[[battery.display]]
threshold = 10
discharging_symbol = ''
style = 'fg:peach bg:crust'

[[battery.display]]
threshold = 5
discharging_symbol = ''
style = 'bold fg:red bg:crust'

[os]
format = '[ $symbol]($style)'
style = 'fg:lavender bg:crust'
disabled = false

[os.symbols]
Arch = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Linux = " "
Macos = " "
NixOS = "󱄅 "
Nobara = " "
Pop = " "
Raspbian = " "
Ubuntu = " "
Unknown = " "

# palette tables should be last in the config ⚓️

# >>> rice palette — generated by gen-palette.py, do not edit >>>
[palettes.rice]
rosewater = "#ffd6ab"
flamingo = "#ffbda5"
pink = "#ffbeeb"
mauve = "#ff85e4"
red = "#ff946b"
maroon = "#ffc4b0"
peach = "#eebe8b"
yellow = "#d2ab63"
green = "#8dc048"
teal = "#35c3c3"
sky = "#61e5e4"
sapphire = "#c3d0ff"
blue = "#93aeff"
lavender = "#bbcbff"
text = "#ebe4e0"
subtext1 = "#ccc5c1"
subtext0 = "#b0aaa6"
overlay2 = "#95908c"
overlay1 = "#797471"
overlay0 = "#4b4745"
surface2 = "#2f2b29"
surface1 = "#282523"
surface0 = "#221f1d"
base = "#1b1917"
mantle = "#151311"
crust = "#0f0e0c"
# <<< rice palette <<<
